customer-service:
  enabled: true
  image:
    tag: "0.0.8-SNAPSHOT"
inventory-service:
  enabled: true
  image:
    tag: "0.0.4-SNAPSHOT"
invoice-service:
  enabled: true
  image:
    tag: "0.0.4-SNAPSHOT"
orchestration:
  enabled: true
  image:
    tag: "0.0.36-SNAPSHOT"
order-service:
  enabled: true
  image:
    tag: "0.0.7-SNAPSHOT"
product-options-service:
  enabled: true
  image:
    tag: "0.0.3-SNAPSHOT"