spring.application.name: "invoice-service"

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  pulsar:
    client:
      service-url: "pulsar://proxys-proxy.pulsar:6650"
    defaults:
      type-mappings:
        - message-type: org.salgar.camunda.invoice.command.InvoiceCommand
          schema-info:
            schema-type: PROTOBUF
        - message-type: org.salgar.camunda.invoice.response.InvoiceResponse
          schema-info:
            schema-type: PROTOBUF
    consumer:
      invoice:
        topics: "persistent://sagatenant/sagans/invoiceInboundTopic"
    producer:
      invoice:
        topic-name: "persistent://sagatenant/sagans/invoiceOutboundTopic"