{{- if .Values.resources.enabled -}}
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarNamespace
metadata:
  name: {{ .Release.Namespace }}-saga-pulsar-namespace
  namespace: {{ .Release.Namespace }}
spec:
  name: sagatenant/sagans
  connectionRef:
    name: {{ .Release.Namespace }}-pulsar-connection
{{- end -}}