{{- if .Values.resources.enabled -}}
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: {{ .Release.Namespace }}-pulsar-product-options-outbound-topic
  namespace: pulsar
spec:
  name: persistent://sagatenant/sagans/productOptionsOutboundTopic
  connectionRef:
    name: {{ .Release.Namespace }}-pulsar-connection
{{- end -}}