{{- if .Values.resources.enabled -}}
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTenant
metadata:
  name: {{ .Release.Namespace }}-saga-pulsar-tenant
  namespace: {{ .Release.Namespace }}
spec:
  name: sagatenant
  connectionRef:
    name: {{ .Release.Namespace }}-pulsar-connection
  adminRoles:
    - admin
    - ops
{{- end -}}